from db_control import insta_db
mydb = insta_db()
db = mydb.db_connect()
#mydb.create_table_location(db)
#mydb.create_table_loc_img(db)
#mydb.create_table_location_image(db)
#mydb.inserting_loc_img(db)
#insta_db.create_table_image_info(db)
#insta_db.insert_location(db)
#insta_db.insert_new_location(db)
#mydb.insert_image(db, "img5.csv")
#mydb.create_table_broken_image(db)
mydb.try_cache_image(db)
#mydb.insert_location(db)
#mydb.create_table_new_location(db)
#mydb.insert_image(db, "img2.csv")
#mydb.insert_loc_img(db)
#mydb.insert_loc_img_1(db)
db.close()
